
<div class="informational">
  <a name="sec_top">&#x200d;</a>
  <h1>Information for you</h1>
  <ul>
    <li><a href="#sec_1" title="SEER (Seasonal Energy Efficiency Ratio)">SEER (Seasonal Energy Efficiency Ratio)</a></li>
    <li><a href="#sec_2" title="Proper AC Unit Size">Proper AC Unit Size</a></li>
    <li><a href="#sec_3" title="Keeping Efficiency Under Control">Keeping Efficiency Under Control</a></li>
    <li><a href="#sec_4" title="Programmable Thermostats: Managing Efficiency">Programmable Thermostats: Managing Efficiency</a></li>
    <li><a href="#sec_5" title="Ceiling Fans: Efficiency Helpers">Ceiling Fans: Efficiency Helpers</a></li>
    <li><a href="#sec_6" title="Rapid Cooling: An Efficiency Myth">Rapid Cooling: An Efficiency Myth</a></li>
    <li><a href="#sec_7" title="Energy-Efficient Upgrades">Energy-Efficient Upgrades</a></li>
    <li><a href="#sec_8" title="Preserving Efficiency: Maintenance and Repair">Preserving Efficiency: Maintenance and Repair</a></li>
  </ul>
  <div>During the cooling season, your AC unit accounts for a large protion of your monthly utility bills. The amount of power it consumes, though, depends on a wide range of factors. Insulation, sizing and maintenance all play a role in determining how much wattage your air conditioner uses, and understanding that power consumption is the first step toward maximizing your HVAC system’s energy efficiency.  As a general reference point, a 3 ton central air conditioner uses around 3500 watts per hour and a 12,000 BTU window unit uses about 1200 watts per hour.</div>
  <a name="sec_1">&#x200d;</a><h2>SEER (Seasonal Energy Efficiency Ratio)<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>SEER is the common method of measuring an air conditioner's energy efficiency rating. SEER is computed as the air conditioner’s cooling output in British thermal units (BTU) divided by its power consumption in watts. SEER values typically range from 10 to 20, with higher ratings denoting more efficient power consumption. To qualify for Energy Star ratings, an air conditioner must have an SEER of at least 14.</div>
  <div>While manufacturers publish a nominal SEER for each model, the effective SEER depends heavily on environmental factors. In homes with different layouts, insulation and load-generating appliances, the same unit may operate at a higher or lower effective SEER. Thus, the SEER a local HVAC technician gives you during the installation process may differ somewhat from the nominal SEER given by the manufacturer.</div>
  <a name="sec_2">&#x200d;</a><h2>Proper AC Unit Size<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>The old adage that <em>bigger isn’t always better</em> certainly holds true in the world of air conditioning. An air conditioner that is too big for your home will constantly cycle on and off, which not only impacts energy efficiency but also leads to uncomfortable temperature changes. Of course, getting an air conditioner that has too little cooling power is even worse; your unit will have to work very hard to keep your home cool and will accumulate plenty of wear and tear in the process. To cool your home efficiently, you need a properly sized air conditioner.</div>
  <div>Because every home is unique, every installation project should begin with a full, professional load calculation. Your home’s cooling load depends on a number of factors, including square footage, layout, insulation and load-generating appliances. By taking all of those factors into account, an HVAC technician can determine exactly how much cooling power you need to maintain a comfortable temperature and recommend a properly sized system to meet those cooling needs. Never just assume that the size of your existing system is correct; the old load calculation may have been wrong, or changing home circumstances may have rendered it obsolete.</div>
  <a name="sec_3">&#x200d;</a><h2>Keeping Efficiency Under Control<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>One of the simplest yet most powerful steps you can take to keep your HVAC systems running efficiently is to properly manipulate your thermostat. Most people can stay comfortable at temperatures between 76 and 79 degrees, so find the warmest temperature that doesn’t bother you and set your thermostat there. Remember, every degree changes your air conditioner’s power consumption by about 7 percent, so it really pays to set the thermostat as high as you can.</div>
  <a name="sec_4">&#x200d;</a><h2>Programmable Thermostats: Managing Efficiency<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>For homeowners who really want to minimize their energy costs, the HVAC industry offers a wide range of precision control devices. A programmable thermostat, for instance, can be set to automatically turn your air conditioning off while the home is empty and turn it back on when you come home from work. Even more advanced thermostats can divide your home into cooling zones, allowing you to shut off the air conditioning in an unused room or turn it up a little in a part of the house that is always warmer than the rest. Some thermostats even offer remote control options, giving you total control over your HVAC system even when you aren’t at home.</div>
  <a name="sec_5">&#x200d;</a><h2>Ceiling Fans: Efficiency Helpers<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>While many homeowners falsely view air conditioners as replacements for ceiling fans, the two devices are in fact complementary. A good ceiling fan helps your air conditioners run more efficiently by improving air circulation throughout the room, constantly removing cold air from the area around the unit and replacing it with hot air that collects near the ceiling. Furthermore, ceilings create an artificial “wind chill” effect that makes the air feel cooler on residents’ skin. With a fan running, you can set your thermostat a degree or two higher without noticing a difference in comfort.</div>
  <div>Ceiling fans with Energy Star ratings are designed inside and out with energy efficiency in mind, so investing in one can really work to reduce your HVAC system’s energy consumption. Remember that many fans have a reverse setting to help your heating equipment run more efficiently, too.</div>
  <a name="sec_6">&#x200d;</a><h2>Rapid Cooling: An Efficiency Myth<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>Many homeowners make the mistake of temporarily setting their thermostats below their target temperature in hopes of cooling their homes down more quickly. In reality, this causes the AC unit to overshoot the target temperature, wasting energy in the process. Once you have a target temperature in mind, stick with it; setting the thermostat lower will not make your air conditioner cool your home more effectively.</div>
  <a name="sec_7">&#x200d;</a><h2>Energy-Efficient Upgrades<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>One of the biggest investments you can make in the future of your home is a more efficient air conditioner. By replacing your old unit with a new model whose SEER is higher, you can substantially reduce your monthly utility bills and enjoy the benefits of more effective cooling. Upgrading from a 10 SEER unit to a 20 SEER can cut your energy costs by as much as 50 percent during the cooling season. Even a more modest upgrade from 12 SEER to 16 SEER reduces your cooling costs by about 25 percent, which can save hundreds of dollars over the course of a year.</div>
  <div>To help you make the most financially sound decision, your HVAC professional may carry out a payback analysis. This calculation divides the cost of purchasing and installing a new system by the monthly utility savings to determine how long it will take for the new system to effectively pay for itself. Using this analysis, many homeowners find that the upgrade to a more efficient air conditioner will pay for itself in just a few years.</div>
  <a name="sec_8">&#x200d;</a><h2>Preserving Efficiency: Maintenance and Repair<a href="#sec_top" title="Back to the listing"></a></h2>
  <div>Even the best air conditioners are prone to minor maintenance issues, and those problems have the potential to seriously impact power consumption. The modern air conditioner is deceptively self-sufficient: It can run for a long time without being serviced, but problems hidden just below the surface cause utility bills to rise and can lead to more expensive issues down the road. On the other hand, a well-maintained air conditioner is an efficient machine that will keep cooling effectively for years to come.</div>
  <div>One of the simplest ways to keep an air conditioner running efficiently is to frequently change the air filter. Over time, air filters can become clogged with dust and debris, preventing air from easily leaving the unit; this forces the machine to work harder and can lead to maintenance issues such as freezing. As a rule, basic filters should be replaced on a monthly basis, while advanced filters should be changed every three months or so. The actual timing may vary depending on smoking, pets, local environment, and general home cleanliness.</div>
  <div>When replacing a disposable air filter, be sure to get a replacement from a factory authorized dealer instead of buying a generic model from a hardware store; using a filter designed to fit your air conditioner will make it run more efficiently. If your air conditioner has a reusable filter, wash it thoroughly with cold water and let it air dry completely before putting it back in the unit.</div>
  <div>Good home maintenance goes a long way, but if you really want to help your air conditioning maintain maximum efficiency, consider investing in a yearly service agreement. Your HVAC professional will come to your home and make the small calibration adjustments your air conditioner needs to cool your home as efficiently as possible. In addition, your technician will diagnose and repair small, hidden issues that could be wasting power. Thus, a service agreement saves you money on your utility bills now and on expensive repairs in the future. With some help from an HVAC professional, your air conditioner will use as little wattage as possible to cool your home.</div>
  <br>
</div>
